In [54]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel
import pandas as pd
import re

In [55]:
def preprocessText(text):
    text = text.lower() # lowercase text
    text = re.sub(r"(.|?)$", "", text) # removing trailing period/question mark from text
    text = re.sub(r"[^A-Za-z\s]{1,}'[A-Za-z]{1,}|[^A-Za-z0-9]{1,}\-[A-Za-z0-9]{1,}|[^A-za-z0-9]{1,}\.[A-za-z0-9]{0,}|[^A-Za-z0-9]{1,}\/[A-Za-z0-9]{1,}|^(#[.]{1,})","", text)
    return text

In [56]:
def normalizeDataset(path_to_dataset):
    dataset = pd.read_csv(path_to_dataset) # read dataset from csv
    
    context, response = dataset['Context'].values, dataset['Response'].values

    for i, text in enumerate(context):
        context[i] = preprocessText(text)
    
    for i, text in enumerate(response):
        response[i] = preprocessText(text)
    
    

In [57]:
def getEmbeddings(input):
    print(f"Prompt: {input}")
    
    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased") # tokenizer
    model = TFBertModel.from_pretrained("bert-base-uncased", use_safetensors=False) # creating BERT model
    encoded_input = tokenizer(input, return_tensors='tf') # encode input
    return model(encoded_input) # return features

In [58]:
def bilstm(embeddings):
    
    model = tf.keras.Sequential([
        embeddings,
        tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, return_sequences=True)),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128)),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

In [ ]:
normalizeDataset("Dataset.csv")

In [ ]:
getEmbeddings("I feel down")

Prompt: I feel down


Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you c

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 5, 768), dtype=float32, numpy=
array([[[-0.11971244,  0.56212956,  0.17869703, ..., -0.15537529,
          0.10191142,  0.13444844],
        [-0.12634909,  0.61109924,  0.30709612, ..., -0.30463475,
          0.5088296 ,  0.01172379],
        [-0.1712548 ,  0.41114804,  0.5559948 , ...,  0.00436866,
          0.08217674,  0.40197086],
        [-0.5413744 ,  0.46206516,  0.3131685 , ...,  0.47742274,
          0.32802358,  0.32806343],
        [ 0.7757725 ,  0.36021987, -0.35929948, ..., -0.05104105,
         -0.6551511 , -0.39173126]]], shape=(1, 5, 768), dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.8262995 , -0.11615644,  0.6850554 ,  0.6289003 , -0.4344623 ,
        -0.09569704,  0.8209331 ,  0.16250552,  0.37083638, -0.99938816,
         0.4391099 ,  0.02300577,  0.9717956 , -0.30550072,  0.9119867 ,
        -0.48169565, -0.14781152, -0.4648432 ,  0.2